name: CML

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  train-and-report:
    runs-on: [self-hosted, cml-gpu]
    timeout-minutes: 50400
    container:
      image: docker://ariefak/real-time_object_classification:latest
      options: --gpus all
    steps:
      - uses: actions/checkout@v4
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Run the training script with python
          python3 Train.py

          # Create a CML report
          echo '![](images/Training/batch_norm_model/batch_norm_model_training_confusion_matrix.png "Confusion Matrix")' >> report.md
          cml comment create report.md